version: 2
updates:
  - package-ecosystem: 'npm'
    target-branch: 'main'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '04:00'
      timezone: Europe/Berlin
    commit-message:
      prefix: 'fix'
      include: 'scope'
    open-pull-requests-limit: 10
    allow:
      - dependency-name: '*stencil*'
      - dependency-name: '*node*'
      - dependency-name: 'colortranslator'
      - dependency-name: 'dotenv'
      - dependency-name: 'prettier'
      - dependency-name: 'eslint-*'
      - dependency-name: 'find'
      - dependency-name: 'tslib'
      - dependency-name: 'sentence-case'
      - dependency-name: 'rxjs'
      - dependency-name: 'reflect-metadata'
      - dependency-name: 'typescript'
      - dependency-name: 'short-unique-id'
      - dependency-name: 'sort-media-queries'
      - dependency-name: 'npm-run-all'
    ignore:
      - dependency-name: '@nrwl/*'
      - dependency-name: 'css-loader'
      - dependency-name: 'style-loader'
      - dependency-name: 'sass-loader'
