/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TfOverlay {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLTfOverlayElement extends Components.TfOverlay, HTMLStencilElement {
    }
    var HTMLTfOverlayElement: {
        prototype: HTMLTfOverlayElement;
        new (): HTMLTfOverlayElement;
    };
    interface HTMLElementTagNameMap {
        "tf-overlay": HTMLTfOverlayElement;
    }
}
declare namespace LocalJSX {
    interface TfOverlay {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "tf-overlay": TfOverlay;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tf-overlay": LocalJSX.TfOverlay & JSXBase.HTMLAttributes<HTMLTfOverlayElement>;
        }
    }
}
