/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonKind } from "./atoms/tf-button/interfaces";
export namespace Components {
    interface PreviewBox {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TfButton {
        /**
          * Active state
         */
        "active": false;
        /**
          * Disabled state
         */
        "disabled": false;
        /**
          * Button kind
         */
        "kind": ButtonKind;
        /**
          * Button type
         */
        "type": string;
    }
    interface TfOverlay {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLPreviewBoxElement extends Components.PreviewBox, HTMLStencilElement {
    }
    var HTMLPreviewBoxElement: {
        prototype: HTMLPreviewBoxElement;
        new (): HTMLPreviewBoxElement;
    };
    interface HTMLTfButtonElement extends Components.TfButton, HTMLStencilElement {
    }
    var HTMLTfButtonElement: {
        prototype: HTMLTfButtonElement;
        new (): HTMLTfButtonElement;
    };
    interface HTMLTfOverlayElement extends Components.TfOverlay, HTMLStencilElement {
    }
    var HTMLTfOverlayElement: {
        prototype: HTMLTfOverlayElement;
        new (): HTMLTfOverlayElement;
    };
    interface HTMLElementTagNameMap {
        "preview-box": HTMLPreviewBoxElement;
        "tf-button": HTMLTfButtonElement;
        "tf-overlay": HTMLTfOverlayElement;
    }
}
declare namespace LocalJSX {
    interface PreviewBox {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TfButton {
        /**
          * Active state
         */
        "active"?: false;
        /**
          * Disabled state
         */
        "disabled"?: false;
        /**
          * Button kind
         */
        "kind"?: ButtonKind;
        /**
          * Event emitted when the item is clicked
         */
        "onClicked"?: (event: CustomEvent<any>) => void;
        /**
          * Button type
         */
        "type"?: string;
    }
    interface TfOverlay {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "preview-box": PreviewBox;
        "tf-button": TfButton;
        "tf-overlay": TfOverlay;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "preview-box": LocalJSX.PreviewBox & JSXBase.HTMLAttributes<HTMLPreviewBoxElement>;
            "tf-button": LocalJSX.TfButton & JSXBase.HTMLAttributes<HTMLTfButtonElement>;
            "tf-overlay": LocalJSX.TfOverlay & JSXBase.HTMLAttributes<HTMLTfOverlayElement>;
        }
    }
}
