name: 'CI: Test UI'

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]
    types: [opened, synchronize, edited, reopened]

jobs:
  ci-test-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: Set yarn version
        run: yarn set version 3.x

      - name: Install dependencies
        run: yarn

      - name: Run ui tests
        run: yarn test themeful-ui
