name: 'Deps: NRWL Update'

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  nrwl-update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: NRWL Update
        id: nrwl_update
        continue-on-error: true
        run: |
          pnpm up @nxext/stencil@latest
          pnpm nrwl:update
          pnpm format

      - name: Check for changes
        run: |
          if [[ -z $(git status -s) ]]; then
            echo "CHANGED_FILES=false" >> $GITHUB_ENV
          else
            echo "CHANGED_FILES=true" >> $GITHUB_ENV
          fi
          echo "LABELS=dependencies,nrwl" >> $GITHUB_ENV
          echo "BRANCH=nrwl_update_$(date +'%Y_%m_%d')" >> $GITHUB_ENV
          echo "TITLE=NRWL Update $(date +'%d.%m.%Y')" >> $GITHUB_ENV

      - name: Add invalid Label
        if: ${{ steps.nrwl_update.outcome == 'failure' }}
        run: echo "LABELS=${{ env.LABELS }},invalid" >> $GITHUB_ENV

      - name: Create Branch
        if: env.CHANGED_FILES == 'true'
        run: |
          git checkout -b ${{ env.BRANCH }}
          git config --global user.email "steinhoff@locity.de"
          git config --global user.name "Marco Steinhoff"
          git add .
          git commit -m'chore(deps): update nrwl'
          git push origin ${{ env.BRANCH }}

      - name: Create Pull Request
        if: env.CHANGED_FILES == 'true'
        run: gh pr create --title '${{ env.TITLE }}' --body '**Automated pull request**' --base main --head ${{ env.BRANCH }} --label '${{ env.LABELS }}'
        env:
          GITHUB_TOKEN: ${{secrets.PAT}}
